feat: make resources configurable by deployment
RedHatInsights/historical-system-profiles-backend pull request #396
Opened 2023-09-11 14:38 UTC by SteveHNH

To optimize resources easily, these values should be made configurable using parameters.

I copied the current settings into the default values in the params so there's no need to change any params in app-interface.

## Secure Coding Practices Checklist Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2023-09-13 08:22 UTC, petrblaho requested changes
Looks good.

There's a need to change that one `m` to `M`.

Also, can you, please, link a ticket for this?

Thank you

2023-09-13 08:22 UTC, petrblaho commented on clowdapp.yaml
> +    value: 512mi
I guess this should be `512Mi`. See `The ClowdApp "historical-system-profiles" is invalid: spec.jobs[0].podSpec.resources.requests.memory: Invalid value: "512mi": spec.jobs[0].podSpec.resources.requests.memory in body should match '^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$'`in https://ci.ext.devshift.net/job/RedHatInsights-historical-system-profiles-backend-pr-check/580/console

2023-09-13 14:19 UTC, petrblaho commented
/retest

2023-09-13 14:40 UTC, SteveHNH commented
Added a JIRA link and fixed the typo in the template

2023-09-13 15:25 UTC, petrblaho commented
/retest

2023-09-14 09:15 UTC, petrblaho commented on clowdapp.yaml
> +  - name: POPULATOR_MEMORY_LIMIT
Tracking here https://issues.redhat.com/browse/RHINENG-2178.

Let's get this merged now.

2023-09-14 09:16 UTC, petrblaho approved these changes

2023-09-14 09:17 UTC, merged