feat: filter HSPs by access to inventory groups
RedHatInsights/historical-system-profiles-backend pull request #429
Opened 2023-10-31 14:21 UTC by romanblanco

https://issues.redhat.com/browse/ESSNTL-5251

## Secure Coding Practices Checklist Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [x] General Coding Practices

2023-12-14 14:26 UTC, petrblaho requested changes

2023-12-14 14:26 UTC, petrblaho commented on historical_system_profiles/views/v1.py
> +        app_name="historical-system-profiles,inventory",
This should not be here. I know I told you to put it here but that was wrong info.
See https://github.com/RedHatInsights/system-baseline-backend/pull/535 and https://issues.redhat.com/browse/RHINENG-5551 for more info.

2023-12-15 11:14 UTC, petrblaho commented
/retest

2023-12-15 12:05 UTC, petrblaho approved these changes

2023-12-15 12:05 UTC, merged

2023-12-15 12:43 UTC, sthirugn commented
awesome thanks!